services:
  backend:
    image: month-4
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - database
  database:
    image: postgres:alpine
    ports:
      - '5432:5433'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
